stages:
  - update

deploy:
  stage: update
  only: 
    - staging
  tags:
    - wp-staging
  script:
    - sudo rsync --remove-source-files -r ./payselection-gateway-for-woocommerce /wordpess-plugin/test
    # - sudo chown -R www-data:www-data ${docs_dir}
    # - sudo rm -rf ${docs_dir}/.git