version: '3.1'
services:
  
  # Database
  database:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_DATABASE: wp
      MARIADB_ROOT_PASSWORD: password

  # WP
  wordpress:
    image: "wordpress:latest"
    depends_on:
      - database
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    links:
      - database
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ./docker/adminer:/var/www/html/adminer/
      - ./woocommerce-ge-gateway:/var/www/html/wp-content/plugins/woocommerce-ge-gateway/

  # WP cli
  cli:
    image: wordpress:cli
    user: "33:33"
    depends_on:
      - database
      - wordpress
    links:
      - database
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      HOME: /tmp
    command: >
      bash -c "
        sleep 15
        chmod 755 /opt/install.sh
        /opt/install.sh
      "
    volumes:
      - wordpress:/var/www/html
      - ./woocommerce-ge-gateway:/var/www/html/wp-content/plugins/woocommerce-ge-gateway/:ro
      - ./docker/bin:/opt

volumes:
  wordpress: